# Generated by Django 6.1 on 2026-09-27 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('politica_privacidade', 'Política de Privacidade'), ('termo_uso', 'Termo de Uso')], max_length=50)),
                ('versao', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('documento_hash', models.CharField(max_length=64)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('instituicao', models.ForeignKey(db_column='instituicao_id', on_delete=django.db.models.deletion.PROTECT, related_name='termos', to='institution.institution')),
            ],
            options={
                'verbose_name': 'Termo',
                'verbose_name_plural': 'Termos',
                'db_table': 'termo',
                'ordering': ['-data_publicacao'],
            },
        ),
        migrations.CreateModel(
            name='AceiteTermo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concedido', models.BooleanField()),
                ('data_concedido', models.DateTimeField(auto_now_add=True)),
                ('data_revogada', models.DateTimeField(blank=True, null=True)),
                ('evidencia', models.JSONField(blank=True, default=dict)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='aceites_termo', to=settings.AUTH_USER_MODEL)),
                ('termo', models.ForeignKey(db_column='termo_id', on_delete=django.db.models.deletion.PROTECT, related_name='aceites', to='privacy.termo')),
            ],
            options={
                'verbose_name': 'Aceite de Termo',
                'verbose_name_plural': 'Aceites de Termo',
                'db_table': 'aceite_termo',
                'ordering': ['-data_concedido'],
            },
        ),
        migrations.AddConstraint(
            model_name='termo',
            constraint=models.UniqueConstraint(fields=('instituicao', 'tipo', 'versao'), name='unique_termo_versao_por_instituicao'),
        ),
    ]
