# Generated by Django 6.1 on 2026-09-27 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoLGPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('revogar_biometria', 'Revogar consentimento biométrico'), ('excluir_conta', 'Excluir minha conta'), ('exportar_dados', 'Exportar meus dados'), ('corrigir_dados', 'Corrigir dados incorretos')], max_length=32)),
                ('justificativa', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_analise', 'Em análise'), ('atendida', 'Atendida'), ('recusada', 'Recusada')], default='pendente', max_length=16)),
                ('resposta_dpo', models.TextField(blank=True)),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_resposta', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_lgpd', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitação LGPD',
                'verbose_name_plural': 'Solicitações LGPD',
                'db_table': 'solicitacao_lgpd',
                'ordering': ['-data_solicitacao'],
            },
        ),
    ]
