# Generated by Django 6.1 on 2026-09-25 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='instituicao',
            field=models.ForeignKey(blank=True, db_column='instituicao_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='institution.institution'),
        ),
    ]
