# Generated by Django 6.1 on 2026-09-26 01:09

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', apps.accounts.models.UsuarioManager()),
            ],
        ),
    ]
