# Generated by Django 6.1 on 2026-09-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usuario_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='totp_ativo',
            field=models.BooleanField(default=False),
        ),
    ]
