# Generated by Django 6.1 on 2026-09-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PresencaRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_token_hash', models.CharField(max_length=64)),
                ('score_facial', models.DecimalField(decimal_places=3, max_digits=4)),
                ('score_vida', models.DecimalField(decimal_places=3, max_digits=4)),
                ('geo_valida', models.BooleanField()),
                ('score_final', models.DecimalField(decimal_places=3, max_digits=4)),
                ('aprovado', models.BooleanField()),
                ('status', models.CharField(max_length=20)),
                ('origem', models.CharField(max_length=50)),
                ('revisado_por', models.IntegerField()),
                ('motivo', models.TextField()),
                ('data_revisao', models.DateTimeField(blank=True, null=True)),
                ('data_decisao', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registro de Presença',
                'verbose_name_plural': 'Registros de Presença',
                'db_table': 'registro_presenca',
            },
        ),
    ]
