# Generated by Django 6.1 on 2026-09-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presencarecord',
            name='revisado_por',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
