# Generated by Django 6.1 on 2026-09-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChamadaSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.IntegerField(default=1)),
                ('abre_em', models.DateTimeField()),
                ('fecha_em', models.DateTimeField()),
                ('duracao_qr_s', models.PositiveSmallIntegerField(default=5)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sessão de Chamada',
                'verbose_name_plural': 'Sessões de Chamada',
                'db_table': 'sessao_chamada',
                'ordering': ['-abre_em'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=20)),
                ('codigo_pareamento', models.CharField(max_length=4, unique=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('visto_em', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Máquina',
                'verbose_name_plural': 'Máquinas',
                'db_table': 'maquina',
            },
        ),
    ]
