# Generated by Django 6.1 on 2026-09-20 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Machine',
        ),
    ]
