# Generated by Django 6.1 on 2026-09-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor_id', models.IntegerField()),
                ('ocorrido_em', models.DateTimeField(auto_now_add=True)),
                ('origem', models.CharField(max_length=50)),
                ('acao', models.CharField(max_length=50)),
                ('tabela', models.CharField(max_length=50)),
                ('linha_tabela_id', models.BigIntegerField()),
                ('payload', models.JSONField()),
                ('hash_anterior', models.CharField(max_length=64)),
                ('hash_atual', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'db_table': 'log_auditoria',
            },
        ),
    ]
