# Generated by Django 6.1 on 2026-09-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='ocorrido_em',
            field=models.DateTimeField(),
        ),
    ]
